# Generated by Django 2.2.6 on 2019-10-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='state',
            new_name='tname',
        ),
    ]
