# Generated by Django 2.2.6 on 2019-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stdno', models.IntegerField()),
                ('Stdname', models.CharField(max_length=30)),
                ('Profpic', models.FileField(blank=True, null=True, upload_to='')),
                ('StdAdd', models.CharField(max_length=30)),
            ],
        ),
    ]
