# Generated by Django 2.2.4 on 2019-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField()),
                ('EmpName', models.CharField(max_length=40)),
                ('Empsal', models.IntegerField()),
                ('EmpAdd', models.CharField(max_length=40)),
            ],
        ),
    ]
