# Generated by Django 2.2.5 on 2019-10-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='Empsal',
            new_name='EmpSal',
        ),
    ]
