# Generated by Django 2.2.6 on 2019-10-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPp', '0002_auto_20191014_0747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter',
            new_name='FilterModel',
        ),
    ]
