# Generated by Django 2.2.6 on 2019-10-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('pname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('drivers', models.ManyToManyField(to='WebApp.Driver')),
            ],
        ),
    ]
