# Generated by Django 2.2.6 on 2019-10-31 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='pname',
            new_name='cname',
        ),
    ]
