# Generated by Django 2.2.6 on 2019-10-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=30)),
                ('Company_logo', models.FileField(blank='Truer', null='True', upload_to='')),
                ('Company_city', models.CharField(max_length=30)),
            ],
        ),
    ]
